# Generated by Django 4.2.6 on 2024-01-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('phone_number', models.CharField(max_length=11)),
                ('student_class', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
