# Generated by Django 4.2.6 on 2024-01-12 08:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='student_class',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('caption', models.CharField(max_length=100)),
                ('Alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni')),
            ],
        ),
    ]
